[package]
name = "sodium_rust_alt"
version = "0.1.0"
authors = ["Clinton Selke <clinuxrulz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"

[dev-dependencies]
env_logger = "0.7.1"